source /usr/share/defaults/etc/profile
alias installpkg='sudo eopkg install'
alias reinstallpkg='sudo eopkg install --reinstall'
alias infopkg='sudo eopkg info'
alias removepkg='sudo eopkg remove'
alias updatepkg='sudo eopkg upgrade'
alias searchpkg='sudo eopkg search'
alias confs='cd ~/.config'
alias pics='cd ~/Pictures'
alias downloads='cd ~/Downloads'
alias cpsc='cd ~/Documents/cpsc'
alias ls='ls --color=auto --group-directories-first'
alias lsa='ls -A --color=auto --group-directories-first'
alias minecraft='java -jar /opt/minecraft/Minecraft.jar'
alias untar='tar -xvf'
alias 4160='cd ~/Documents/cpsc/4160'
alias 4240='cd ~/Documents/cpsc/4240'
alias 4300='cd ~/Documents/cpsc/4300'
alias ece3520='cd ~/Documents/cpsc/ece3520'
alias ..='cd ..'
alias rmorphans='sudo eopkg remove-orphans'
alias r='ranger'
alias neo='neofetch'
alias 4910='cd ~/Documents/cpsc/4910'
alias youtube='youtube-viewer'
alias dragon='~/Documents/misc/./dragon.sh'
alias makec='make clean'
alias re='reset'
alias l='ls'
alias 4620='cd ~/Documents/cpsc/4620'
